#!/usr/bin/env bash
#A script that display numbers from 1-100 but display FizzBuzz when multiple of 3 and 5, display Fizz when mulitple of 3, display buzz when multiple of 5

for i in {1..100}
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
