#!/usr/bin/env bash
#A script that displays content of file /etc/password and only display it's username,user id and home dir path for user.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
