#!/usr/bin/env bash
#A script that displays number 1 -20 but "bad luck from china" for the 4th iteration and bad luck from japan on 9th iteration and bad luck from italy on 17th iteration

num=1

while [ $num -le 20 ]
do
	echo "$num"
	case $num in
		"4") echo "bad luck from china";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from italy";;
	esac
	(( num++ ))
done
